version: "3.7"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    container_name: postgres
    image: postgres:10.6-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres # comment if no need to persist data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    
  roadmap-service:
    container_name: roadmap-service
    build: ./RoadmapService
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=Roadmap;User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      RabbitMq__Host: "rabbitmq"
      RabbitMq__UserName: "guest"
      RabbitMq__Password: "guest"
      RabbitMq__HistoryQueueName: "history_queue"
      RabbitMq__HistoryExchangeName: "history_exchange"
      RabbitMq__HistoryWaypointRoutingKey: "new_waypoint_routing_key"
      RabbitMq__NotificationQueueName: "notification_queue"
      RabbitMq__NotificationExchangeName: "new_notification_exchange"
      RabbitMq__NotificationWaypointRoutingKey: ""